[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
gringotts = "D4qgtRF5t7MzA5nASfag3ef5Y68xb5hBcp9ac9Wttfkr"

[programs.devnet]
gringotts = "D4qgtRF5t7MzA5nASfag3ef5Y68xb5hBcp9ac9Wttfkr"

[programs.testnet]
gringotts = "D4qgtRF5t7MzA5nASfag3ef5Y68xb5hBcp9ac9Wttfkr"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init = "ts-node --transpile-only ./scripts/init.ts"
price = "ts-node --transpile-only ./scripts/get_price.ts"
estimate = "ts-node --transpile-only ./scripts/estimate.ts"
bridge = "ts-node --transpile-only ./scripts/bridge.ts"
withdraw = "ts-node --transpile-only ./scripts/withdraw.ts"
