[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
gringotts = "BFKTaMXC9GiM2nydmYfNLTaxr2WTzANQH888G3dYbW6W"

[programs.localnet]
gringotts = "BFKTaMXC9GiM2nydmYfNLTaxr2WTzANQH888G3dYbW6W"

[programs.mainnet]
gringotts = "Up3RApFZC654LGNSjKtEgVVdsfW7XANLaYFjP81vShM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
bridge = "ts-node --transpile-only ./scripts/bridge.ts"
bridge-prod = "ts-node --transpile-only ./scripts/bridge-prod.ts"
estimate = "ts-node --transpile-only ./scripts/estimate.ts"
init = "ts-node --transpile-only ./scripts/init.ts"
init-prod = "ts-node --transpile-only ./scripts/init-prod.ts"
price = "ts-node --transpile-only ./scripts/get_price.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
withdraw = "ts-node --transpile-only ./scripts/withdraw.ts"
